version: 1.0.{build}
image: Visual Studio 2019

install:
- cmd: dotnet tool install -g dotnet-script

build_script:
- cmd: >-
    cd build

    refreshenv

    dotnet script build.csx

artifacts:
- path: build\Artifacts\NuGet\*.nupkg
  name: NuGet Packages

test: off
environment:
    IS_SECURE_BUILDENVIRONMENT:
        secure: xYC5jpSucUdHr8YwfxWefw==
    GITHUB_REPO_TOKEN:
        secure: FSPXTPuTgFMaZA7DubJoX217SkWhFLN2BGqCCi4gBux967eFtwkhbrafm7ay8cP2
    NUGET_APIKEY:
        secure: JfKADiDMHJBIYRnlh56cqh0HCqCRmeI6XJtFfGSPUltPNs5BDfAvkTC2mmckhUbK